### ISSUE TITLE
Exception loading sessions from persistent storage

### ISSUE THREAD

**Issue by cicciu** [OsiriX-Foundation/karnak#127]
ERROR     [restartedMain] org.apache.juli.logging.DirectJDKLog: Exception loading sessions from persistent storage
java.io.InvalidClassException: java.util.Collections$UnmodifiableCollection; invalid descriptor for field c
	at java.base/java.io.ObjectStreamClass.readNonProxy(ObjectStreamClass.java:829)
	at java.base/java.io.ObjectInputStream.readClassDescriptor(ObjectInputStream.java:971)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1971)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1868)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1999)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1868)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2161)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1685)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2498)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2392)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2193)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1685)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2498)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2392)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2193)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1685)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:499)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:457)
	at org.apache.catalina.session.StandardSession.doReadObject(StandardSession.java:1587)
	at org.apache.catalina.session.StandardSession.readObjectData(StandardSession.java:1040)
	at org.apache.catalina.session.StandardManager.doLoad(StandardManager.java:218)
	at org.apache.catalina.session.StandardManager.load(StandardManager.java:162)
	at org.apache.catalina.session.StandardManager.startInternal(StandardManager.java:354)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5194)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:451)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:200)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:181)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:159)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:144)
	at org.karnak.StartApplication.main(StartApplication.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.IllegalArgumentException: illegal signature
	at java.base/java.io.ObjectStreamField.<init>(ObjectStreamField.java:124)
	at java.base/java.io.ObjectStreamClass.readNonProxy(ObjectStreamClass.java:827)
	... 67 common frames omitted

**Comment by cicciu** [comment]
https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#server.servlet.session.persistent

https://stackoverflow.com/questions/20622746/exception-loading-sessions-from-persistent-storage

put to `false` `server.servlet.session.persistent` To disable session persistence during restarts
